language: python
python:
 - 2.7
 - 3.3
 - 3.4
install:
 - pip install -r requirements-dev.txt
 - python setup.py develop
script: py.test --cov pyoes --cov-report term-missing
after_success: coveralls
