language: python
python:
 - "2.7"
 - "3.5"
notifications:
 email:
    - vanderhaegen.cedrik@vlaanderen.be
env:
 - LC_ALL=en_US.utf-8
install:
 - pip install -r requirements-dev.txt
 - python setup.py develop
script: py.test --cov pyoes --cov-report term-missing
after_success: coveralls
