os: linux
dist: focal
language: python
python:
  - "3.8"
notifications:
 email:
    - vanderhaegen.cedrik@vlaanderen.be
env:
 - LC_ALL=en_US.utf-8
install:
 - pip install -r requirements-dev.txt
 - python setup.py develop
script:
 - ./check_versions.sh
 - py.test --cov pyoes --cov-report term-missing
after_success: coveralls
