#!/usr/bin/env bash
#
# pip_compile.sh - regenerate the requirements*.txt files from pyproject.toml.
#
# Dependencies are declared in pyproject.toml; this recompiles the pinned
# requirement files with uv (a fast pip-compile drop-in). Run it after changing
# the dependencies in pyproject.toml.
#
#   requirements.txt      -> runtime only        (no extras)
#   requirements-ci.txt   -> CI                  (--extra dev)
#   requirements-dev.txt  -> local development   (--extra dev)
#
# pyoes only depends on public PyPI packages, so - unlike the other OE repos -
# no internal pypi index (and therefore no VPN) is needed here.
#
set -euo pipefail

cd "$(dirname "$0")/.."

# Always use the uv pinned by mise (latest), not whatever uv happens to be on
# PATH: the flags of an older uv inside an activated virtualenv differ.
# mise exec selects the repo's uv regardless of the active environment.
# This requires mise to be installed; without it the command below errors out.
UV=(mise exec -- uv)

# --no-header drops the autogenerated header. uv does not emit index URLs into
# the output by default, so the generated files stay clean. We still strip the
# trailing "unsafe packages" footer if one is emitted.
COMMON=(--no-header --quiet)

compile() {
    local out="$1"; shift
    "${UV[@]}" pip compile "${COMMON[@]}" "$@" -o "${out}" pyproject.toml
    # Strip the "# The following packages are considered to be unsafe ..." footer.
    sed -i '/^# The following packages are considered to be unsafe/,$d' "${out}"
    # Drop a possible trailing blank line left behind.
    sed -i -e :a -e '/^\n*$/{$d;N;ba}' "${out}"
    echo "  -> ${out}"
}

echo "Compiling requirements.txt (runtime)"
compile requirements.txt

echo "Compiling requirements-ci.txt (dev extra)"
compile requirements-ci.txt --extra dev

echo "Compiling requirements-dev.txt (dev extra)"
compile requirements-dev.txt --extra dev

echo "Done."
